title: LEAN
subtitle: Alternative Energy and Nanomaterials
description: An engaging 1-3 sentence description of your lab.
header: null
footer: images/site/barra_inferior.jpg
links:
  email: contact@your-lab.com
  twitter: YourLabHandle
  instagram: YourLabHandle
  youtube: YourLabChannel
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@labeansite.com
github: labeansite
twitter: labeansite
instagram: labeansite
youtube: labeansite
