- id: doi:10.1016/s1872-2067(21)63973-6
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1872206721639736-fx1.jpg
  tags:
    - tag teste

- id: doi:10.1002/cnma.202100510
  image: https://onlinelibrary.wiley.com/cms/asset/11e367a3-a174-4e2c-852e-7d6b622f197f/cnma202100510-toc-0001-m.jpg
#  tags:
#    - tag teste

- id: doi:10.1149/2162-8777/ac6114
#  image: 
#  tags:
#    - tag teste

- id: doi:10.3390/nano12121957
  image: https://www.mdpi.com/nanomaterials/nanomaterials-12-01957/article_deploy/html/images/nanomaterials-12-01957-g001-550.jpg
#  tags:
#    - tag teste

- id: doi:10.1039/D0RA10176A
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D0RA10176A&imageInfo.ImageIdentifier.Year=2021 
#  tags:
#    - tag teste

- id: doi:10.1021/acs.jpcc.0c11397
  image: https://pubs.acs.org/cms/10.1021/acs.jpcc.0c11397/asset/images/medium/jp0c11397_0009.gif
#  tags:
#    - tag teste

- id: doi:10.1063/5.0049914
  image: https://aip.scitation.org/action/showOpenGraphArticleImage?doi=10.1063/5.0049914&id=images/medium/5.0049914.figures.online.highlight_f1.jpg
#  tags:
#    - tag teste

- id: doi:10.1021/acs.chemmater.0c04305
  image: https://pubs.acs.org/cms/10.1021/acs.chemmater.0c04305/asset/images/medium/cm0c04305_0010.gif 
#  tags:
#    - tag teste

- id: doi:10.1063/5.0060483
  image: https://aip.scitation.org/action/showOpenGraphArticleImage?doi=10.1063/5.0060483&id=images/medium/5.0060483.figures.online.highlight_f1.jpg
#  tags:
#    - tag teste

- id: doi:10.1063/5.0066931
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB0fX-qkbFAOXj__P-P515lOhrLtBsh-B7wT4V2WyaQLGkP1hzHjk7k3W9EdyLnr5w5v0&usqp=CAU
#  tags:
#    - tag teste

- id: doi:10.1002/cphc.201901171
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/d86a0600-e768-40b2-8ad7-6f18da4a2d0b/cphc201901171-toc-0001-m.png 
#  tags:
#    - tag teste

- id: doi:10.1016/j.solmat.2019.110378
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0927024819307044-sc1.jpg 
#  tags:
#    - tag teste

- id: doi:10.1016/j.solmat.2020.110428
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0927024820300349-fx1.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.solmat.2019.110377
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0927024819307032-gr1.jpg
#  tags:
#    - tag teste

- id: doi:10.1002/cctc.202000143
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/0272f24a-a327-4ceb-bb49-5b2ee0f2af3c/cctc202000143-toc-0001-m.png 
#  tags:
#    - tag teste

- id: doi:10.1063/5.0003146
  image: https://aip.scitation.org/na101/home/literatum/publisher/aip/journals/content/apm/2020/apm.2020.8.issue-4/5.0003146/20200407/images/medium/5.0003146.figures.online.f1.jpg
#  tags:
#    - tag teste

- id: doi:10.1021/acs.jpcc.9b11966
  image: https://pubs.acs.org/cms/10.1021/acs.jpcc.9b11966/asset/images/medium/jp9b11966_0007.gif
#  tags:
#    - tag teste

- id: doi:10.1016/j.enconman.2020.112975
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0196890420305197-ga1.jpg
#  tags:
#    - tag teste

- id: doi:10.1002/ces2.10062
  image: https://ceramics.onlinelibrary.wiley.com/cms/asset/ab725179-3acd-4e0a-9a7f-d22f3b2e730f/ces210062-fig-0001-m.png
#  tags:
#    - tag teste

- id: doi:10.1063/5.0015519
  image: https://aip.scitation.org/action/showOpenGraphArticleImage?doi=10.1063/5.0015519&id=images/medium/5.0015519.figures.online.highlight_f1.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.jcat.2020.08.014
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0021951720303250-ga1.jpg
#  tags:
#    - tag teste

- id: doi:10.1021/acsanm.0c01957
  image: https://pubs.acs.org/cms/10.1021/acsanm.0c01957/asset/images/medium/an0c01957_0010.gif
#  tags:
#    - tag teste

- id: doi:10.1111/jace.17390
  image: https://ceramics.onlinelibrary.wiley.com/cms/asset/14c00c5b-e07e-43a1-88af-aa3556c3e411/jace17390-toc-0001-m.jpg?trick=1675687835311
#  tags:
#    - tag teste

- id: doi:10.1016/j.jcat.2018.12.010
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0021951718304901-ga1.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.jcat.2019.02.030
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0021951719300910-ga1.jpg
#  tags:
#    - tag teste

- id: doi:10.1002/aelm.201900065
  image: https://onlinelibrary.wiley.com/cms/asset/33af4df6-3707-4c50-928e-e697a4e59786/aelm201900065-gra-0001-m.jpg?trick=1670785209110
#  tags:
#    - tag teste

- id: doi:10.1016/j.jallcom.2019.05.335
#  image: 
#  tags:
#    - tag teste

- id: doi:10.1039/C9TA05452A
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C9TA05452A&imageInfo.ImageIdentifier.Year=2019
#  tags:
#    - tag teste

- id: doi:10.1016/j.matlet.2019.07.068
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0167577X19310547-ga1.jpg
#  tags:
#    - tag teste

- id: doi:10.1021/acs.jpclett.9b02928
  image: https://pubs.acs.org/cms/10.1021/acs.jpclett.9b02928/asset/images/medium/jz9b02928_0005.gif
#  tags:
#    - tag teste

- id: doi:10.1590/0001-3765201820170581
  image: https://minio.scielo.br/documentstore/1678-2690/tYKv5XjMsTfysjJhGVdxfKR/058fcf17e52f0d7897875ae7cc1e334070f91e41.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.matchemphys.2018.02.044
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0254058418301482-egi10SGKL50T8Q.jpg
#  tags:
#    - tag teste

- id: doi:10.1002/slct.201800383
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/bc0f9f66-caac-4b7c-bf3a-23c70b0f6180/slct201800383-toc-0001-m.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.ceramint.2018.09.097
  image: https://ars.els-cdn.com/content/image/1-s2.0-S027288421832563X-gr1.jpg
#  tags:
#    - tag teste

- id: doi:10.1039/C7RE00183E
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C7RE00183E&imageInfo.ImageIdentifier.Year=2018
#  tags:
#    - tag teste

- id: doi:10.1039/C7RA03277C
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C7RA03277C&imageInfo.ImageIdentifier.Year=2017
#  tags:
#    - tag teste

- id: doi:10.1039/C7CP04827K
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C7CP04827K&imageInfo.ImageIdentifier.Year=2017
#  tags:
#    - tag teste

- id: doi:10.1088/1361-6528/aa8b5d
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuyU7nO75Yq8hFbu-RkrJO__ep3S0JbPs48UrNNNc2p59lUfFGeLyyFVmWCIsngmeNCaQ&usqp=CAU
#  tags:
#    - tag teste

- id: doi:10.1016/j.jeurceramsoc.2017.10.041
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0955221917307215-gr6.jpg
#  tags:
#    - tag teste

- id: doi:10.1039/C7CP06558B
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C7CP06558B&imageInfo.ImageIdentifier.Year=2017
#  tags:
#    - tag teste

- id: doi:10.1016/j.solmat.2015.09.028
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0927024815004614-fx1.jpg
#  tags:
#    - tag teste

- id: doi:10.1002/cphc.201500659
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/ef184a42-1ad7-4587-a46b-2c3c6764ccd7/cphc201500659-toc-0001-m.png
#  tags:
#    - tag teste

- id: doi:10.1039/C5TA06646H
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C5TA06646H&imageInfo.ImageIdentifier.Year=2016
#  tags:
#    - tag teste

- id: doi:10.1016/j.jallcom.2016.03.008
#  image: 
#  tags:
#    - tag teste

- id: doi:10.1016/j.tsf.2016.03.011
#  image: 
#  tags:
#    - tag teste

- id: doi:10.1002/cphc.201600316
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/7863e603-af5d-44a3-87ac-b1144ff44af9/cphc201600316-toc-0001-m.png
#  tags:
#    - tag teste

- id: doi:10.1016/j.ceramint.2016.06.035
  image: http://cdmf.org.br/wp-content/uploads/2016/06/FEG-images-of-fractured-PZT-ceramic-bodies-sintered-in-conventional-and-microwave-ovens-1.jpg
#  tags:
#    - tag teste

- id: doi:10.1021/acsami.6b11950
  image: https://pubs.acs.org/cms/10.1021/acsami.6b11950/asset/images/medium/am-2016-11950h_0008.gif
#  tags:
#    - tag teste

- id: doi:10.1557/jmr.2015.353
  image: https://static.cambridge.org/content/id/urn%3Acambridge.org%3Aid%3Aarticle%3AS0884291415003532/resource/name/S0884291415003532_figAb.jpeg?pub-status=live
#  tags:
#    - tag teste

- id: doi:10.1557/jmr.2013.302
  image: https://static.cambridge.org/binary/version/id/urn:cambridge.org:id:binary-alt:20160922085019-92071-mediumThumb-S0884291413003026_fig1g.jpg?pub-status=live
#  tags:
#    - tag teste

- id: doi:10.1039/C3RA42753F
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C3RA42753F&imageInfo.ImageIdentifier.Year=2014 
#  tags:
#    - tag teste

- id: doi:10.1002/cphc.201300054
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/ec149d89-2a6c-489a-a876-3d6a586e87e5/mcontent.gif
#  tags:
#    - tag teste

- id: doi:10.1016/j.jallcom.2013.04.126
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0925838813010384-fx1.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.tsf.2013.04.034
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0040609013006500-gr5.jpg
#  tags:
#    - tag teste

- id: doi:10.1371/journal.pone.0076857
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/3793907/bin/pone.0076857.g003.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.jpowsour.2012.01.093
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0378775312001929-gr1.jpg
#  tags:
#    - tag teste

- id: doi:10.1021/am301425e
  image: https://pubs.acs.org/cms/10.1021/am301425e/asset/images/medium/am-2012-01425e_0007.gif
#  tags:
#    - tag teste

- id: doi:10.1021/jp202101r
  image: https://pubs.acs.org/cms/10.1021/jp202101r/asset/images/medium/jp-2011-02101r_0001.gif 
#  tags:
#    - tag teste

- id: doi:10.1016/j.matchemphys.2011.06.040
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0254058411005578-gr2.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.matchemphys.2010.08.030
  image: https://d3i71xaburhd42.cloudfront.net/acbc17cf3c9498a83a5baa2f9152deab6f26e038/2-Figure3-1.png
#  tags:
#    - tag teste

- id: doi:10.1016/j.solmat.2008.11.049
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0927024808004479-gr1.jpg
#  tags:
#    - tag teste

- id: doi:10.1039/B811946E
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=B811946E&imageInfo.ImageIdentifier.Year=2009
#  tags:
#    - tag teste

- id: doi:10.1002/cphc.200700629
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/71d90234-af61-4970-913c-fd9270041713/mcontent.gif
#  tags:
#    - tag teste

- id: doi:10.1063/1.3023061
  image: https://aip.scitation.org/action/showOpenGraphArticleImage?doi=10.1063/1.3023061&id=images/medium/1.3023061.figures.f1.gif
#  tags:
#    - tag teste

- id: doi:10.1002/cphc.200700260
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/4dea3080-81a3-4313-8ead-0aa34cf1baea/mcontent.gif
#  tags:
#    - tag teste

- id: doi:10.1016/j.solmat.2007.06.011
  image: https://www.researchgate.net/profile/Michel-Aegerter/publication/237277011/figure/fig2/AS:299454700769288@1448406972201/a-Z-0-versus-Z-00-impedance-complex-plane-plots-for-SPHP-with-1_Q320.jpg
#  tags:
#    - tag teste

- id: doi:10.1016/j.electacta.2007.04.063
  image: https://www.researchgate.net/profile/Michel-Aegerter/publication/222817637/figure/fig5/AS:341647859699716@1458466605261/Transmittance-T-b-and-T-c-of-the-ECIII-device-at-l-550-nm-as-a-function-of-the-CA_Q320.jpg
#  tags:
#    - tag teste

- id: doi:10.1021/cm051003j
#  image: 
#  tags:
#    - tag teste

- id: doi:10.1016/j.ssi.2003.10.009
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0167273803004764-gr3.sml
#  tags:
#    - tag teste

- id: doi:10.1063/1.1765854
  image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsh7wpgm2qytDLl0_BnpTSApbQUgJDUNFxElFx3IPiXHIqnEvGinukyaoR7B2K8BhaBiI&usqp=CAU
#  tags:
#    - tag teste

- id: doi:10.1016/S0254-0584(03)00083-X
  image: https://ars.els-cdn.com/content/image/1-s2.0-S025405840300083X-gr1.sml
#  tags:
#    - tag teste

- id: doi:10.1371/journal.pcbi.1007128
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  repo: greenelab/meta-review
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
